# Generated by Django 2.2.24 on 2021-10-21 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0031_event_legacy_registration_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registration",
            old_name="photo_consent",
            new_name="LEGACY_photo_consent",
        ),
    ]
