# Generated by Django 2.1.11 on 2019-10-11 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0008_joblisting_youtube_url'),
        ('users', '0021_auto_20190829_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='joblistings.Joblisting'),
        ),
    ]
