# Generated by Django 2.1.11 on 2019-10-11 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0008_joblisting_youtube_url'),
        ('users', '0022_user_subscriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='joblistings.Joblisting'),
        ),
    ]
